jobs:
  build:
    if: github.ref != 'refs/heads/master'
    name: Maven Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Cache Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mvn
        path: '~/.m2/repository

          ~/.sonar/cache

          '
        restore-keys: '${{ runner.os }}-mvn-

          '
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.2
    - continue-on-error: true
      name: Build with Maven
      run: 'mvn verify \

        --batch-mode \

        --file portfolio-app/pom.xml

        '
  build-analyze:
    if: github.ref == 'refs/heads/master'
    name: Maven Build + Sonar Analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Cache Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-mvn
        path: '~/.m2/repository

          ~/.sonar/cache

          '
        restore-keys: '${{ runner.os }}-mvn-

          '
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.2
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build with Maven
      run: 'mvn verify sonar:sonar \

        --batch-mode \

        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \

        --file portfolio-app/pom.xml

        '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
